# Numpy 学习笔记

## ndarray 介绍

ndaaray全称为 N-dimensional array，这是Numpy中由**相同类型的元素**组成的多维数组，**元素的数量是事先指定好的**。

元素的数据类型是由dtype(data-type)对象来指定的；数组的大小固定，在创建指定好后不再发生变化。

In [1]:
import numpy as np

In [11]:
a = np.array([[1,0,1],[2,1,2]])
print(a)

[[1 0 1]
 [2 1 2]]


## ndarray属性

- ndim: 维度数量
- shape: 数组的形状
- dtype: 数组元素数据类型
- size: 元素总个数

ndarray中shape属性可以依据数组中各个`[ ]`中含有的`[ ]`数目来确定

In [12]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)

2
(2, 3)
int64
6


# ndarray的创建

## 基础创建方式

- array函数：接受普通的Python列表
- zeros函数：创建指定长度或者形状的全0数组
- ones函数：创建指定长度或者形状的全1数组
- empty函数：创建未初始化的数组

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.empty((2,3))

array([[4.67983657e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

## 其他创建方式

- arrange函数：类似于Python中的range函数，指定**开始值、终值和步长**来创建一维数组
- linspace函数：指定**开始值、终值和元素个数**来创建一维数组
- logspace函数：和linspace函数相类似，不过创建的是等比数列
- numpy.random模块的random函数：创建随机数组

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(0,5,2)

array([0, 2, 4])

In [19]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.logspace(0,10,5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [22]:
np.random.random((2,2))

array([[0.71215361, 0.0736221 ],
       [0.52945713, 0.59648251]])

# 属性修改

## 数据类型

创建Numpy数组时候Numpy会默认指定数据类型，或者可以显式的利用dtype属性指定数据类型。

利用`astype`可以**修改元素属性**：

In [30]:
b = np.array([1,2,3])
b.dtype

dtype('int64')

In [24]:
b2 = b.astype(float)
b2.dtype

dtype('float64')

## ndarray形状修改

- 直接修改ndarray的shape值
- 使用reshape进行修改，虽然修改时原数组shape不变，但是二者共享内存空间，因此修改一个也会影响另一个

当指定新数组某一轴元素为-1时，将根据元素个数自动计算此轴长度。

In [26]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
np.arange(0,10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
b.shape

(3,)

In [32]:
b.shape = (3,1)

In [33]:
b

array([[1],
       [2],
       [3]])

# Numpy基本操作

