<a href="https://colab.research.google.com/github/ZacharyXue/Code-Backup/blob/main/Numpy%E5%AE%9E%E8%B7%B5_%E7%AC%94%E8%AE%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

原文链接：https://tianchi.aliyun.com/course/323

# 第一章：数据类型及数组创建

## 常量

`numpy.nan`表示空值，两个`nan`变量不相等。

In [ ]:
np.nan == np.nan

False

In [ ]:
x = np.array([1,2,np.nan,4])
np.isnan(x)

array([False, False,  True, False])

与`nan`类似的还有`inf`、`pi`、`e`等等。

## 根据现有数据创建`ndarry`

In [ ]:
y = np.asarray(x)
y

array([1, 2, 3, 4])

`asarray()`和`array()`不同在于当数据源是 ndarray时`asarray()`创建数组不会重新拷贝副本。

## 依据特定函数填充方式

特定函数有很多，类似于`ones()`（全是1）、`zeros()`（全是0）和`eye()`（对角元素为1）等等，具体可以等到用的时候再查。

以`ones()`举例用法：

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## 利用数值范围创建数组

比较常用的是`arange`产生等差数列：

In [ ]:
np.arange(4,12,2)

array([ 4,  6,  8, 10])

numpy也有可以产生等比数列：

In [ ]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

关于产生随机矩阵，这里有好多种，具体用的时候可以在numpy官方查找。

In [ ]:
np.random.random([3,2])

array([[0.11982752, 0.15399235],
       [0.63273084, 0.27242302],
       [0.69771025, 0.03937506]])

## 数组的属性

In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

数组的性质种最常用的是其`shape`：

In [ ]:
x.shape

(3, 3)

除此之外还有：

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.size

9

In [ ]:
x.ndim

2

# 第二章 索引、切片和迭代

要注意数组切片返回的是原数组的视图，对切片元素进行修改就是对原数组进行修改。

In [ ]:
x = np.random.random([3,3,3])
x

array([[[0.33830667, 0.69811605, 0.49248288],
        [0.60665212, 0.46158694, 0.07204195],
        [0.52038049, 0.82854518, 0.168616  ]],

       [[0.53135717, 0.10891768, 0.65438404],
        [0.02678069, 0.19206225, 0.72739482],
        [0.52048883, 0.87817465, 0.20153047]],

       [[0.16315454, 0.78697886, 0.63216706],
        [0.33134797, 0.96375149, 0.00644335],
        [0.55562463, 0.45784154, 0.3608314 ]]])

In [ ]:
x[1:,1:,2] = 0
x

array([[[0.33830667, 0.69811605, 0.49248288],
        [0.60665212, 0.46158694, 0.07204195],
        [0.52038049, 0.82854518, 0.168616  ]],

       [[0.53135717, 0.10891768, 0.65438404],
        [0.02678069, 0.19206225, 0.        ],
        [0.52048883, 0.87817465, 0.        ]],

       [[0.16315454, 0.78697886, 0.63216706],
        [0.33134797, 0.96375149, 0.        ],
        [0.55562463, 0.45784154, 0.        ]]])

当方括号中传入多个索引值时，可以同时选择多个元素

In [ ]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
y[[1,4,5]]

array([1, 4, 5])

除此之外我们可以使用布尔索引来获得相应元素

In [ ]:
y > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [ ]:
y[ y > 5 ]

array([ 6,  7,  8,  9, 10, 11])

# 第三章 数组操作

## 更改数组形状

最简单的便是`reshape`，但是numpy中还提供了`flatten([order='C'])`等等，很多实际上都可以使用`reshape`代替，看了一遍后觉得还是使用`reshape`，这样开始的时候难度不会太大。

## 更改数组维度

当创建一个数组之后，还可以给它增加一个维度，官方举例：
> 很多工具包在进行计算时都会先判断输入数据的维度是否满足要求，如果输入数据达不到指定的维度时，可以使用newaxis参数来增加一个维度。

这个我经常在不同尺寸计算利用广播机制时使用，还是比较实用的一个性质。

In [ ]:
x = np.arange(5)
y = x[np.newaxis,:]
y.shape

(1, 5)

In [ ]:
y = x[:,np.newaxis]
y.shape

(5, 1)

In [ ]:
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 数组的合并

这个我也好几次遇到了，这里会使用`numpy.concatenate((a1, a2, ...), axis=0, out=None)`

In [ ]:
x = np.array([1, 2, 3])
y = np.array([7, 8, 9])
np.concatenate([x,y])

array([1, 2, 3, 7, 8, 9])

默认 `axis = 0`。

In [ ]:
x = x.reshape(1,3)
y = y.reshape(1,3)
np.concatenate([x,y])

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
x.shape,y.shape

((1, 3), (1, 3))

In [ ]:
np.concatenate([x,y]).shape

(2, 3)

In [ ]:
np.concatenate([x,y],axis=1)

array([[1, 2, 3, 7, 8, 9]])

In [ ]:
np.concatenate([x,y],axis=1).shape

(1, 6)

从上面可以看出，`axis` 等于多少，合并的时候便是哪个维度进行相加减，其他维度应该是相等的。

## 数组拆分

`numpy.split(ary, indices_or_sections, axis=0)`

`indices_or_sections` int or 1-D array

If indices_or_sections is **an integer**, N, the array will be divided into **N equal arrays** along axis. If such a split is not possible, an error is raised.

If indices_or_sections is a **1-D array** of sorted integers, the entries indicate where along axis the array is split. For example, [2, 3] would, for axis=0, result in

- ary[:2]

- ary[2:3]

- ary[3:]

In [ ]:
x = np.arange(12).reshape(3,4)
x.shape

(3, 4)

In [ ]:
np.split(x,[1,2])

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
np.split(x,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
np.split(x,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

# 第四章 数学函数及逻辑函数

## 逻辑函数

真值测验

In [ ]:
x = np.arange(12).reshape(3,4)
y = np.arange(12,0,-1).reshape(3,4)

In [ ]:
np.all(x==y,axis=0)

array([False, False, False, False])

In [ ]:
np.any(x==y,axis=1)

array([False,  True, False])

数组内容

In [ ]:
x = np.array([1,2,3,np.nan])
np.isnan(x)

array([False, False, False,  True])

## 广播

广播的机制有：
- 如果两个数组的维度数dim不相同，那么小维度数组的形状将会在**左边**补1。
- 如果shape维度不匹配，但是有维度是1，那么可以扩展维度是1的维度匹配另一个数组；
- 如果shape维度不匹配，但是没有任何一个维度是1，则匹配引发错误。

In [ ]:
x = np.arange(4)
y = np.ones((3,4))
(x+y).shape

(3, 4)

In [ ]:
x = np.arange(3)
y = np.ones((3,4))
(x+y).shape

ValueError: ignored

从上面可以发现广播机制只能够在左边添加维度而不能在右边添加维度。

In [ ]:
x = np.arange(4).reshape(1,4)
y = np.ones((3,4))
(x+y).shape

(3, 4)

In [ ]:
x = np.ones((2,4))
y = np.ones((4,4))
(x+y).shape

ValueError: ignored

从上面可以发现广播机制只能将维度为1的进行扩展，对于其他的均不能。

In [ ]:
x = np.arange(4).reshape(4, 1)
y = np.ones(5)
(x + y).shape

(4, 5)

从上面可以发现，广播机制是从右边开始匹配，`x`的`shape[-1]=1`而`y`的`shape[-1]=5`，故对`x`进行广播，然后`x`的`shape[0]=4`而`y`的`shape[0]=None`，故对`y`再进行广播。

## 算数函数

首先numpy有很多类似于`add`、`multiply`等等的运算函数，但是感觉开始的时候并不需要记忆，因为直观的使用+、-、*、/等能够达到同样的效果。

In [ ]:
x = np.arange(10)
y = np.arange(1,11)
x + y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.add(x,y)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
x = np.random.random((3,4))
y = np.random.random((4,3))

np.matmul(x,y) == x @ y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

上面关于numpy矩阵矩阵乘法的运算，之前只知道`matmul()`这个，前两天在知乎上看到`@`也可以表示矩阵乘法，这样一下子就简洁很多。

numpy中还有指数函数、对数函数、三角函数等等，这些可以在需要使用的时候再去numpy doc查找。一般来讲这类的用法都很简单，感觉熟能生巧就好，没必要记忆。

比较需要注意的一类是加法函数,其中`sum`是根据axis进行操作，axis等于几就在该轴进行操作；而`cumsum()`在加上cum前缀后会把加法操作的每一步都显式的显示出来，不止`sum()`，`prod()`等等都是这样的。

不经让联想到like，像`ones_like()`等等，可以输入一个矩阵，然后就可以输出该矩阵shape的特定矩阵。

In [ ]:
x = np.arange(12).reshape(3,4)
np.sum(x)

66

In [ ]:
np.sum(x,axis=0)

array([12, 15, 18, 21])

In [ ]:
np.sum(x,axis=1)

array([ 6, 22, 38])

In [ ]:
np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [ ]:
np.cumsum(x,axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

`prod()`是用于矩阵内求累乘结果：

In [ ]:
np.prod(x[1:,]) # 因为元素有0，直接计算结果为0

6652800

相似的还有`diff()`，用于求矩阵内元素差值。

有一个感觉比较有用但是没有用过的是`clip(a, a_min, a_max, out=None, **kwargs)`函数，这个函数可以对矩阵内元素进行修剪，我记得RNN里面讲过对梯队的修剪。

In [ ]:
np.clip(x,5,10)

array([[ 5,  5,  5,  5],
       [ 5,  5,  6,  7],
       [ 8,  9, 10, 10]])

# 第五章 排序，搜索和计数

## 排序

### numpy.sort()

最简单最基础的就是`sort()`了，`numpy.sort(a[, axis=-1, kind='quicksort', order=None])`，其中kind表示排序方法，order表示排序的字段名。

In [ ]:
x = np.random.random((3,4))
x

array([[0.21551154, 0.36021939, 0.98967085, 0.02223871],
       [0.81106705, 0.59749857, 0.28094851, 0.62687202],
       [0.01114364, 0.86642825, 0.29220774, 0.258713  ]])

一定一定要注意axis的设置。

In [ ]:
np.sort(x,axis=0)

array([[0.01114364, 0.36021939, 0.28094851, 0.02223871],
       [0.21551154, 0.59749857, 0.29220774, 0.258713  ],
       [0.81106705, 0.86642825, 0.98967085, 0.62687202]])

In [ ]:
np.sort(x,axis=1)

array([[0.02223871, 0.21551154, 0.36021939, 0.98967085],
       [0.28094851, 0.59749857, 0.62687202, 0.81106705],
       [0.01114364, 0.258713  , 0.29220774, 0.86642825]])

### numpy.argsort()

有时候我们会想用元素的索引位置替代排序后的实际结果，比如要shuffle数据的时候，需要同时将label和data进行shuffle，但很多时候两者是分开的，这时候使用`argsort()`就会使得操作方便很多。

`numpy.argsort(a[, axis=-1, kind='quicksort', order=None]) `

In [ ]:
np.argsort(x)

array([[3, 0, 1, 2],
       [2, 1, 3, 0],
       [0, 3, 2, 1]])

## 搜索

`numpy.argmax(a[, axis=None, out=None])`

`numpy.argmin(a[, axis=None, out=None])`

In [ ]:
x = np.arange(12).reshape(3,4)
np.argmax(x)

11

In [ ]:
np.argmax(x,axis=0)

array([2, 2, 2, 2])

In [ ]:
np.argmax(x,axis=1)

array([3, 3, 3])

`numpy.where(condition, [x=None, y=None])`

 Return elements chosen from x or y depending on condition.

In [ ]:
np.where(x<5,x,-x)

array([[  0,   1,   2,   3],
       [  4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11]])

## 集合操作

`numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)` 

Find the unique elements of an array.
- return_index=True 表示返回新列表元素在旧列表中的位置。
- return_inverse=True表示返回旧列表元素在新列表中的位置。
- return_counts=True表示返回新列表元素在旧列表中出现的次数。


In [ ]:
np.unique([[1,2,3,2,1],[1,2,3,3,2],[1,2,3,2,2]])

array([1, 2, 3])

In [ ]:
np.unique([[1,2,3,2,1],[1,2,3,3,2],[1,2,3,2,2]],axis=1)

array([[1, 1, 2, 2, 3],
       [1, 2, 2, 3, 3],
       [1, 2, 2, 2, 3]])

In [ ]:
np.unique([[1,2,3,2,1],[1,2,3,3,2],[1,2,3,2,2]],axis=0)

array([[1, 2, 3, 2, 1],
       [1, 2, 3, 2, 2],
       [1, 2, 3, 3, 2]])

# 第九章 线性代数

`numpy.dot(a, b[, out])`

计算两个矩阵的乘积，如果是一维数组则是它们的内积。

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])
np.dot(x, y)

70

`numpy.linalg.eig(a)` 计算方阵的特征值和特征向量。

`numpy.linalg.eigvals(a)` 计算方阵的特征值。

In [ ]:
x = np.diag((1, 2, 3)) 
np.linalg.eigvals(x)

array([1., 2., 3.])

In [ ]:
np.linalg.eig(x) 

(array([1., 2., 3.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

`u, s, v = numpy.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)`

奇异值分解
- a 是一个形如(M,N)矩阵
- full_matrices的取值是为False或者True，默认值为True，这时u的大小为(M,M)，v的大小为(N,N)。否则u的大小为(M,K)，v的大小为(K,N) ，K=min(M,N)。
- compute_uv的取值是为False或者True，默认值为True，表示计算u,s,v。为False的时候只计算s。
- 总共有三个返回值u,s,v，u大小为(M,M)，s大小为(M,N)，v大小为(N,N)，a = u*s*v。
- 其中s是对矩阵a的奇异值分解。s除了对角元素不为0，其他元素都为0，并且对角元素从大到小排列。s中有n个奇异值，一般排在后面的比较接近0，所以仅保留比较大的r个奇异值。

注：Numpy中返回的v是通常所谓奇异值分解a=u*s*v'中v的转置。

In [ ]:
A = np.array([[4, 11, 14], [8, 7, -2]])
u, s, vh = np.linalg.svd(A, full_matrices=False)

In [ ]:
u

array([[-0.9486833 , -0.31622777],
       [-0.31622777,  0.9486833 ]])

In [ ]:
s

array([18.97366596,  9.48683298])

In [ ]:
vh

array([[-0.33333333, -0.66666667, -0.66666667],
       [ 0.66666667,  0.33333333, -0.66666667]])