# Numpy 学习笔记

## ndarray 介绍

ndaaray全称为 N-dimensional array，这是Numpy中由**相同类型的元素**组成的多维数组，**元素的数量是事先指定好的**。

元素的数据类型是由dtype(data-type)对象来指定的；数组的大小固定，在创建指定好后不再发生变化。

In [2]:
import numpy as np

In [11]:
a = np.array([[1,0,1],[2,1,2]])
print(a)

[[1 0 1]
 [2 1 2]]


## ndarray属性

- ndim: 维度数量
- shape: 数组的形状
- dtype: 数组元素数据类型
- size: 元素总个数

ndarray中shape属性可以依据数组中各个`[ ]`中含有的`[ ]`数目来确定

In [12]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)

2
(2, 3)
int64
6


# ndarray的创建

## 基础创建方式

- array函数：接受普通的Python列表
- zeros函数：创建指定长度或者形状的全0数组
- ones函数：创建指定长度或者形状的全1数组
- empty函数：创建未初始化的数组

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.empty((2,3))

array([[4.67983657e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

## 其他创建方式

- arrange函数：类似于Python中的range函数，指定**开始值、终值和步长**来创建一维数组
- linspace函数：指定**开始值、终值和元素个数**来创建一维数组
- logspace函数：和linspace函数相类似，不过创建的是等比数列
- numpy.random模块的random函数：创建随机数组

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(0,5,2)

array([0, 2, 4])

In [19]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.logspace(0,10,5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [22]:
np.random.random((2,2))

array([[0.71215361, 0.0736221 ],
       [0.52945713, 0.59648251]])

# 属性修改

## 数据类型

创建Numpy数组时候Numpy会默认指定数据类型，或者可以显式的利用dtype属性指定数据类型。

利用`astype`可以**修改元素属性**：

In [30]:
b = np.array([1,2,3])
b.dtype

dtype('int64')

In [24]:
b2 = b.astype(float)
b2.dtype

dtype('float64')

## ndarray形状修改

- 直接修改ndarray的shape值
- 使用reshape进行修改，虽然修改时原数组shape不变，但是二者共享内存空间，因此修改一个也会影响另一个

当指定新数组某一轴元素为-1时，将根据元素个数自动计算此轴长度。

In [26]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
np.arange(0,10).reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
b.shape

(3,)

In [32]:
b.shape = (3,1)

In [33]:
b

array([[1],
       [2],
       [3]])

# Numpy基本操作

## 数组和标量、数组之间的运算

Numpy中的矩阵运算要比直接用Python内置的方法要快得多。

数组和标量之间运算:

In [3]:
arr1 = np.array([1,2,3,4,5,6]).reshape((2,3))
arr1 + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [4]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

同等大小数组间运算:

In [5]:
arr2 = np.ones((2,3))
arr1 + arr2

array([[2., 3., 4.],
       [5., 6., 7.]])

## 数组的矩阵积

Numpy中的矩阵积使用符合线性代数中的相关概念，这里需要使用的方法是 `dot()`。

In [6]:
arr2.shape = (3,2)
arr1.dot(arr2)

array([[ 6.,  6.],
       [15., 15.]])

## 数组的索引和切片

对于Numpy多维数组的索引，这里也有两种方式进行，其实大同小异，注意一下就好：

In [9]:
arr1[1,1]

5

In [10]:
arr1[1][1]

5

还有一种比较特殊的索引方式：**布尔型索引**:

In [14]:
arr1 % 2 == 0

array([[False,  True, False],
       [ True, False,  True]])

In [15]:
arr1[arr1 % 2 == 0]

array([2, 4, 6])

另外还有**花式索引**，是利用整数数组进行索引：

In [16]:
arr1[:,[0,2]]

array([[1, 3],
       [4, 6]])

数组的切片规则和Python中的完全一样：

In [12]:
arr1[:,0:2]

array([[1, 2],
       [4, 5]])

## 数组的转置

In [17]:
arr1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
arr1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

## 通用函数

在数组中可以使用一些简单的函数来执行对于数组元素的数学操作，例如：

In [20]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

常见的一元通用函数有：

|一元ufunc|解释|
|:-:|:-|
|abs,fabs|绝对值计算，对于非复数时使用fabs更快|
|sqrt|计算平方根|
|exp|计算个元素的指数e的x次方|
|log，log10，log2|计算底为自然对数、10、2的对数|
|isnan、isfinite、isinf|对于数组元素进行判断|

常见的二元通用函数：

|二元ufunc|解释|
|:-:|:-|
|divide、floor_divide|除法或者向下圆整除（丢弃余数）|
|pow|计算第一个数组元素的第二个数组对应元素的次方|
|maximum,fmax|fmax会忽略NaN|
|minimun、fmin||
|mod|元素级的取余|
|greater、greater_equal、less、less_equal、equal、not_equal|元素级的比较运算|
|logical_and、logical_or、logical_xor|元素级的布尔逻辑运算|

## 聚合函数

聚合函数是对于指定的数组的某个轴进行操作。

In [23]:
arr1.mean()

3.5

In [24]:
arr1.mean(axis=0)

array([2.5, 3.5, 4.5])

In [25]:
arr1.mean(axis=1)

array([2., 5.])

In [26]:
arr1.sum()

21

In [27]:
arr1.std()

1.707825127659933

In [28]:
arr1.max()

6

In [29]:
arr1.min()

1

## np.where函数

np.where函数是三元表达式 x if condition else y 的矢量化版本。

In [31]:
np.where(arr1 % 2 == 0, -1 , arr1)

array([[ 1, -1,  3],
       [-1,  5, -1]])

## np.unique函数

np.unique函数用于求数组中的不重复元素：

In [32]:
np.unique(arr2)

array([1.])

In [33]:
np.unique(arr1)

array([1, 2, 3, 4, 5, 6])

# 数组文件的读写

如果将数组保存至二进制文件，则有：

In [34]:
np.save('data',arr1)

In [35]:
np.load('data.npy')

array([[1, 2, 3],
       [4, 5, 6]])

如果要将数组保存至文本文件，则有：

In [36]:
np.savetxt('data.csv',arr1,delimiter=',')

In [37]:
np.loadtxt('data.csv',delimiter=',')

array([[1., 2., 3.],
       [4., 5., 6.]])